# Generated by Django 5.0.6 on 2024-07-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_inf_tec', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('enlaces_fotos', models.URLField(blank=True)),
                ('enlaces_videos', models.URLField(blank=True)),
                ('id_mecanico', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
                ('orden_servicio', models.CharField(max_length=100)),
            ],
        ),
    ]
